install.packages("rnaturalearth")

library(readxl)
library(tidyverse)
library(ggplot2)
library(here)
library(dplyr)
library(sf)
library(rnaturalearth)
library(viridis)
library(ggrepel)

source(here("scripts","importing.R"))
source(here("scripts","wrangling.R"))
source(here("scripts","visualize.R"))