install.packages("readxl")
install.packages("tidyverse")
install.packages("ggplot2")
install.packages("here")
install.packages("dplyr")
install.packages("sf")
install.packages("rnaturalearth")
install.packages("viridis")
install.packages("ggrepel")

library(readxl)
library(tidyverse)
library(ggplot2)
library(here)
library(dplyr)
library(sf)
library(rnaturalearth)
library(viridis)
library(ggrepel)

source(here("scripts","importing.R"))
source(here("scripts","wrangling.R"))


source(here("scripts","visualize.R"))